version: '3'

services:
  cf-module:
    build:
      context: .
      dockerfile: Dockerfile

    restart: always
    
    ports:
      - 50054:50054

    networks:
      - embers


networks:
  embers:
    driver: bridge  