name: market-grpc-module
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip=
  - colorama=
  - cvxpy=1.2.2
  - matplotlib=
  - pyscipopt=4.2.0
  - scipy=1.9.3
  - jinja2=
  - jsonpickle=
  - numpy=
  - pandas=
  - mpld3=
  - pydantic=
  - pip:
    - grpcio==1.44.0
    - protobuf==3.20.1
    - gurobipy==9.5.1
    - python-dateutil
    - python-dotenv
    - coptpy